### ISSUE TITLE
开启 acl graph && 使能 xpu graph nd2nz patten 后报错：RuntimeError: Cannot run aclop operators during NPU graph capture.

### ISSUE THREAD

**Issue by wwens7** [BD-Seed-HHW/xpu_graph#304]
### Describe the bug🐛

复现脚本：
```python
import torch
import torch_npu
import torchair as tng
from torchair.configs.compiler_config import CompilerConfig

from xpu_graph.compiler import XpuGraph, XpuGraphConfig, Target
from xpu_graph.test_utils import (
    is_similar,
)

xpu_graph_backend = XpuGraph(
                    XpuGraphConfig(
                    is_training=False,
                    debug=True,
                    target=Target.npu,
                    dump_graph=True,
                    freeze=True,
                    vendor_compiler_config={
                        "mode": "reduce-overhead", # acl graph
                        "compiler": "ge" 
                    },
            )
        )

device = 'npu'
dtype = torch.float16

class TorchMmModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        weight1 = torch.randn(128, 64, dtype=dtype, device=device)
        weight2 = torch.randn(64, 32, dtype=dtype, device=device)
        self.register_buffer("weight1", weight1, persistent=True)
        self.register_buffer("weight2", weight2, persistent=True)

    def forward(self, x):
        # First mm operation: x (batch, 128) @ weight1 (128, 64) -> (batch, 64)
        intermediate = torch.mm(x, self.weight1)
        # Second mm operation: intermediate (batch, 64) @ weight2 (64, 32) -> (batch, 32)
        result = torch.mm(intermediate, self.weight2)
        return result

x = torch.randn(16, 128, dtype=dtype, device=device)
module = TorchMmModule().to(device)
result_direct = module(x)

with torch.no_grad():
    compiled_module = torch.compile(module, backend=xpu_graph_backend, dynamic=False)
    result_compiled = compiled_module(x)

assert is_similar(result_direct.cpu(), result_compiled.cpu(), rtol=1e-2, atol=1e-2)
```
以上脚本测试了一个简单的 nd-nz 转换功能：对于 torch.mm的常量 weights，使用 xpu graph 中的 nd-nz patten 对其进行转换。

现象 1：直接运行脚本，即开启 acl graph && 使能 nd-nz patten，程序报错：

> RuntimeError: Cannot run aclop operators during NPU graph capture. Current working aclop is MatMul. If you need this call to be captured, please try to set torch.npu.config.allow_internal_format = False. If still fail, the operator needs aclnn implementation and please file an issue. Current npuStreamCaptureStatus: npuStreamCaptureStatusActive
[ERROR] 2025-07-04-11:54:22 (PID:2419547, Device:0, RankID:-1) ERR00007 PTA feature not supported

_根据报错信息，猜测原因是权重变成 NZ 格式后，在图捕获阶段 torch.mm 被 dispatch 到了 aclop 接口而不是 aclnn，而 aclop 不支持成图？_
根据提示，在脚本中添加：
`torch.npu.config.allow_internal_format = False`
运行正常
`assert is_similar(result_direct.cpu(), result_compiled.cpu(), rtol=1e-2, atol=1e-2) #pass`

现象 2：注释with torch.no_grad():，即开启 acl graph && 关掉 nd-nz patten，程序正常运行

这里有三个 concern：
1. 虽然添加torch.npu.config.allow_internal_format = False后运行正常，但是根据字面意思，这个config 似乎是禁用了 internal format，为什么结果依然 close？
2. 在 xpu_graph 内，使用 acl graph 时是否需要加上torch.npu.config.allow_internal_format = False？（如是，在哪里加比较好）会不会对其他功能/patten 有影响？（补充：https://www.hiascend.com/document/detail/zh/Pytorch/600/comref/comaq/commonqa_0023.html 中提到会对性能有一定影响）
### Environment details

-

**Comment by yfchen-byted** [comment]
如果使用`torch.npu.config.allow_internal_format = False`会发生什么

**Comment by wwens7** [comment]
使用torch.npu.config.allow_internal_format = False 的情况补充在上面了，之前在 xpu graph 的xpu_graph/xpu_graph/backends/npu.py 中：
```python
def ge_compiler(module: torch.nn.Module, example_inputs, config_dict, **kwargs) -> torch.nn.Module:
    import torch.fx as fx
    import torch_npu

    torch.npu.set_compile_mode(jit_compile=False)

    import torchair as tng
    import torchair.ge_concrete_graph.ge_converter.experimental.patch_for_hcom_allreduce
    from torchair.configs.compiler_config import CompilerConfig

    config = CompilerConfig()
    if config_dict.get("mode", None) == "reduce-overhead":
        config.mode = config_dict["mode"]
        torch.npu.config.allow_internal_format = False # here！！！！！
        from torch import SymInt

        for ele in example_inputs:
            if isinstance(ele, SymInt):
                raise TypeError("ACL Graph does not support dynamic shape!!")
    else:
        """
        TODO(zhangjihang): We have to use this, cause some case we have to use GE
        """
        config.experimental_config.keep_inference_input_mutations = True
        config.experimental_config.frozen_parameter = True
    npu_backend = tng.get_npu_backend(compiler_config=config)
    compiled_module = npu_backend(module, example_inputs)

    return compiled_module
```
加了torch.npu.config.allow_internal_format = False，但似乎没生效。在测试脚本里加上就好了。。

**Comment by nalinaly** [comment]
torch_npu当前遵循如下逻辑：
基于历史原因：torch_npu的算子有两个方式，一个是aclOp方式（支持nz格式但是编译时间较长现在日落中），一个是aclnn方式（可以无需在线编译直接调用但是支持nz格式的功能还在逐步完善中）

如果用户对权重做了nd-nz的转换之后，在aclnn的API支持NZ之前就会被torch_npu路由到aclOp分支上去
但是aclOp方式由于早期设计原因，workspace是在其API内部获取无法保证aclgraph期间的内存不变，因此在torch_npu的aclgraph capture阶段做了拦截aclOp的处理避免静默内存踩踏行为

如果加上torch.npu.config.allow_internal_format = False，当前导致的实际行为会变成本质上的nd-nz失败（但是不会报错），因此看似导致aclgraph capture成功，但其实不是预期的结果的效果

完整的matmul入参支持nz功能的aclnn方式，当前还在开发过程中，有这个aclnn支持matmul NZ功能后才能使用aclgraph场景下使用matmul的nz权重提升性能方式，具体版本行为请找支撑人员核实一下。

**Comment by wwens7** [comment]
get

**Comment by nalinaly** [comment]
"mode": "reduce-overhead"，实质上走的是aclgraph逻辑（依赖aclnn matmul支持nz入参）
default的mode是"max-autotune"，走的是GE逻辑，GE因为当前已经具备接受入参nz tensor的能力因此而不报错。

**Comment by wwens7** [comment]
get

**Comment by wwens7** [comment]
又试了一下default mode(aka GE)下跑 quant matmul，会有如下报错：

> Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch_npu/dynamo/torchair/_utils/error_code.py", line 43, in wapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torch_npu/dynamo/torchair/core/_backend.py", line 123, in compile
    return super(TorchNpuGraph, self).compile()
RuntimeError: E40021: [PID: 2544330] 2025-07-04-14:50:35.119.251 Failed to compile Op [QuantBatchMatmulV3]. (oppath: [Compile /usr/local/Ascend/ascend-toolkit/8.0.T112/opp/built-in/op_impl/ai_core/tbe/impl/dynamic/quant_batch_matmul_v3.py failed with errormsg/stack: File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tikcpp/ascendc_common_utility.py", line 480, in dump_build_log
    raise Exception("An error occurred during compile phases of {}, msg is {}".\
Exception: An error occurred during compile phases of CompileStage.PRECOMPILE, msg is <built-in>:1:10: fatal error: '__clang_cce_runtime_wrapper.h' file not found
#include "__clang_cce_runtime_wrapper.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
], optype: [QuantBatchMatmulV3])
        Solution: See the host log for details, and then check the Python stack where the error log is reported.
        TraceBack (most recent call last):
        Compile op[QuantBatchMatmulV3] failed, oppath[/usr/local/Ascend/ascend-toolkit/8.0.T112/opp/built-in/op_impl/ai_core/tbe/impl/dynamic/quant_batch_matmul_v3.py], optype[QuantBatchMatmulV3], taskID[4]. Please check op's compilation error message.[FUNC:ReportBuildErrMessage][FILE:fusion_manager.cc][LINE:368]
        [SubGraphOpt][Compile][ProcFailedCompTask] Thread[140551696815872] recompile single op[QuantBatchMatmulV3] failed[FUNC:ProcessAllFailedCompileTasks][FILE:tbe_op_store_adapter.cc][LINE:1137]
        [SubGraphOpt][Compile][ParalCompOp] Thread[140551696815872] process fail task failed[FUNC:ParallelCompileOp][FILE:tbe_op_store_adapter.cc][LINE:1184]
        [SubGraphOpt][Compile][CompOpOnly] CompileOp failed.[FUNC:CompileOpOnly][FILE:op_compiler.cc][LINE:1198]
        [GraphOpt][FusedGraph][RunCompile] Failed to compile graph with compiler Normal mode Op Compiler[FUNC:SubGraphCompile][FILE:fe_graph_optimizer.cc][LINE:1415]
        Call OptimizeFusedGraph failed, ret:4294967295, engine_name:AIcoreEngine, graph_name:partition1_rank1_new_sub_graph3[FUNC:OptimizeSubGraph][FILE:graph_optimize.cc][LINE:119]
        subgraph 0 optimize failed[FUNC:OptimizeSubGraphWithMultiThreads][FILE:graph_manager.cc][LINE:861]
        [Call][PreRun] Failed, graph_id:0, session_id:1.[FUNC:CompileGraph][FILE:graph_manager.cc][LINE:4544]
        [Compile][Graph]Compile graph failed, error code:1343225857, session_id:1, graph_id:0.[FUNC:CompileGraph][FILE:ge_api.cc][LINE:1280]

看起来是环境问题，但在"mode": "reduce-overhead"是正常的，尝试过source set_env.sh没用，求解

**Comment by wwens7** [comment]
问题原因：当前 tritonx 1.0 中集成了与 cann 包同名的 bisheng 编译器等组件，导致ge 进行图编译时头文件冲突。
解决：@mingfa 计划于 7.7 进行修复
